FROM node:15.13-alpine
ENV NODE_ENV developement
LABEL version="1.0"
LABEL description="Docker for Frontend"
LABEL maintainer=["Martin Flasar"]

WORKDIR /client
ENV PATH="./node_modules/.bin:$PATH"
COPY "package*.json" "./"

RUN npm ci

COPY ./ ./

EXPOSE 3000
RUN npm run build
CMD ["npm", "start"]