FROM node:15.13-alpine
ENV NODE_ENV developement
LABEL version="1.0"
LABEL description="Docker for server"
LABEL maintainer = ["christian.flasar@gmail.com"]

WORKDIR /server

COPY ["package.json", "package-lock.json", "./"]

RUN npm ci

COPY ./ ./

EXPOSE 3001

CMD ["node", "index.js"]